// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RedditBackend.Entities;
using System;

namespace RedditBackend.Migrations
{
    [DbContext(typeof(RedditContext))]
    [Migration("20180125160457_AddConnections")]
    partial class AddConnections
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RedditBackend.Models.Post", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Timestamp");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.Property<long?>("UserId");

                    b.Property<long?>("VotesVoteId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VotesVoteId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("RedditBackend.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RedditBackend.Models.Vote", b =>
                {
                    b.Property<long>("VoteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Score");

                    b.Property<long?>("UserId");

                    b.HasKey("VoteId");

                    b.HasIndex("UserId");

                    b.ToTable("Vote");
                });

            modelBuilder.Entity("RedditBackend.Models.Post", b =>
                {
                    b.HasOne("RedditBackend.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId");

                    b.HasOne("RedditBackend.Models.Vote", "Votes")
                        .WithMany("Posts")
                        .HasForeignKey("VotesVoteId");
                });

            modelBuilder.Entity("RedditBackend.Models.Vote", b =>
                {
                    b.HasOne("RedditBackend.Models.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
