// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Quiz.Entities;
using System;

namespace Quiz.Migrations
{
    [DbContext(typeof(QuizContext))]
    [Migration("20180131141242_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Quiz.Models.QuizModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CorrectAnswer");

                    b.Property<string>("FirstAnswer");

                    b.Property<string>("FourthAnswer");

                    b.Property<string>("Question");

                    b.Property<string>("SecondAnswer");

                    b.Property<string>("ThirdAnswer");

                    b.HasKey("Id");

                    b.ToTable("QuizModels");
                });
#pragma warning restore 612, 618
        }
    }
}
